os:
- linux

language: java

script:
- export CXX="/usr/bin/g++-4.8"
- export CC="/usr/bin/gcc-4.8"
- "./setup.sh"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libsqlite3-dev
    - zlib1g-dev
    - libbz2-dev
    - liblzma-dev

notifications:
  email:
    recipients:
    - daniel@neus-online.eu
